Movie Rating System

In [5]:
import numpy as np
np.set_printoptions(formatter={"float_kind":"{:.3f}".format})#sets the display setting so that all the float vaues will have 3 values after decimal


creating numpy array of 1000 movie ids

In [6]:
movie_id = np.arange(2301,3301)
print(movie_id[:10])
print(movie_id.size)

[2301 2302 2303 2304 2305 2306 2307 2308 2309 2310]
1000


creating 100 user ids

In [7]:
user_id=[]
for i in range(23400,23500):
    user_id.append(i)
user_id=np.array(user_id)
print(user_id)

[23400 23401 23402 23403 23404 23405 23406 23407 23408 23409 23410 23411
 23412 23413 23414 23415 23416 23417 23418 23419 23420 23421 23422 23423
 23424 23425 23426 23427 23428 23429 23430 23431 23432 23433 23434 23435
 23436 23437 23438 23439 23440 23441 23442 23443 23444 23445 23446 23447
 23448 23449 23450 23451 23452 23453 23454 23455 23456 23457 23458 23459
 23460 23461 23462 23463 23464 23465 23466 23467 23468 23469 23470 23471
 23472 23473 23474 23475 23476 23477 23478 23479 23480 23481 23482 23483
 23484 23485 23486 23487 23488 23489 23490 23491 23492 23493 23494 23495
 23496 23497 23498 23499]


In [8]:
print(user_id.size)

100


creatimg a movie_matrix, to store user ratings such that
there are hundred users 
each user can review as many movies as they want
the review should be in between 0 and 10
the movies which are not reviewed are given a value of -1

In [9]:
import random
movie_matrix=[]
for user in range(100):
    movies_rated_by_me=np.full(1000,-1)
    num_of_movies_rated=random.randint(0,999)
    movies_that_i_will_rate=random.sample(range(0,1000),num_of_movies_rated)
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index]=random.randint(0,10)
    movie_matrix.append(movies_rated_by_me)

In [10]:
movie_matrix

[array([-1,  7, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1,  7, -1, -1, -1, -1,  7, -1, 10,
        -1,  5,  2,  8, -1, -1, -1, -1,  5, -1, -1, -1,  2, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  9, -1, -1, -1, -1, -1,
        -1, -1, -1,  3, -1,  7, -1, -1,  0, -1, -1,  1, -1, -1, -1, -1, -1,
        -1, -1,  0, -1, -1, -1,  0, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1,
         7, -1, -1, -1, -1, -1,  0, -1,  2, -1, -1,  0, -1, -1, -1, -1, -1,
        -1, -1, -1,  8, -1, -1, -1, -1, -1,  7, -1, -1, -1, -1, -1,  2, -1,
         8, -1, -1, -1,  6, -1, -1, -1, -1, -1, -1, -1, 10,  9, -1, -1, -1,
        -1, -1,  5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  9, -1,
        10, -1, -1,  8, -1, -1, -1, -1,  5, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1,  9, -1, -1, -1, -1, -1, -1,  2, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, -1, -1, -1,  4, -1, -1,  3,
        -1, 

In [11]:
movie_matrix=np.array(movie_matrix)
print(movie_matrix.shape)#shape of the array

(100, 1000)


In [12]:
print(len(movie_matrix))#length of the movie

100


In [13]:
type(movie_matrix)

numpy.ndarray

In [14]:
movie_matrix[:3]

array([[-1,  7, -1, ..., -1, -1, -1],
       [ 5,  4,  2, ...,  4, 10,  2],
       [-1, -1, -1, ..., -1, -1, -1]])

In [15]:
print(movie_matrix.size)#no. of elements in the matrix

100000


In [16]:
print(movie_matrix.ndim)#no. of dimensions

2


adding the reviwes of 10 movie experts and 50 more movies////

creating a matrix of 10 movie experts

In [26]:
expert_matrix=[]
for user in range(10):
    movies_rated_by_me=np.full(1000,-1)
    num_of_movies_rated=random.randint(0,999)
    movies_that_i_will_rate=random.sample(range(0,1000),num_of_movies_rated)
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index]=random.randint(0,10)
    expert_matrix.append(movies_rated_by_me)
expert_matrix=np.array(expert_matrix)
print(expert_matrix)
print(expert_matrix.size)
print(expert_matrix.shape)
print(type(expert_matrix))
print(len(expert_matrix))

[[-1  8 -1 ... -1  3 -1]
 [ 2 -1  5 ...  0  9  9]
 [ 1  1 -1 ...  6  0  7]
 ...
 [ 3 -1  5 ...  3 -1  9]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1  4]]
10000
(10, 1000)
<class 'numpy.ndarray'>
10


In [28]:
movie_matrix=np.vstack([movie_matrix,expert_matrix])

In [29]:
movie_matrix.shape

(110, 1000)

adding 50 more movies 

In [40]:
new_movie_matrix=[]
for user in range(110):
    movie_rated_by_me=np.full(50,-1)
    num_of_movies_rated=random.randint(0,49)
    movies_that_i_will_rate=random.sample(range(0,50),num_of_movies_rated)
    for index in movies_that_i_will_rate:
        movie_rated_by_me[index]=random.randint(0,10)
    new_movie_matrix.append(movie_rated_by_me)
new_movie_matrix=np.array(new_movie_matrix)
print(new_movie_matrix)
print(new_movie_matrix.shape)
print(new_movie_matrix.size)
print(type(new_movie_matrix))

[[ 4  5  5 ...  6  9  7]
 [-1  6 -1 ... -1 -1  6]
 [ 2  9 -1 ...  8 -1  9]
 ...
 [-1 -1  3 ... -1 -1 -1]
 [ 2  4 -1 ... -1  2  9]
 [ 4 -1 -1 ...  0  7  4]]
(110, 50)
5500
<class 'numpy.ndarray'>


In [42]:
new_movies_id=np.append(movie_id,np.arange(2301,2351))
new_movies_id.size

1050

In [43]:
movie_matrix=np.hstack([movie_matrix,new_movie_matrix])
print(movie_matrix.shape)

(110, 1050)


creating final movie rating with four columns

In [46]:
final_movie_rating=[]
for i in range(1050):
    m=movie_matrix[:,i]
    m=m[m>=0]
    total_num_rating=m.size
    avg_rating=m.mean()
    standard_deviation=m.std()
    final_movie_rating.append([new_movies_id[i],avg_rating,total_num_rating,standard_deviation])
final_movie_rating=np.array(final_movie_rating)

In [47]:
final_movie_rating

array([[2301.000, 4.607, 56.000, 3.183],
       [2302.000, 5.018, 55.000, 2.806],
       [2303.000, 4.765, 51.000, 3.147],
       ...,
       [2348.000, 4.814, 59.000, 3.133],
       [2349.000, 4.578, 45.000, 3.429],
       [2350.000, 4.700, 60.000, 3.242]])

convert the final movie ratings to have range from 0 to 10,such that the minimum ratings converts to 0 and maximum converts to 10,others values in between

In [51]:
x=final_movie_rating[:,1]
old_range=x.max()-x.min()
new_range=(10-0)
final_movie_rating[:,1]=((x-x.min())*(new_range/old_range)+0)

In [52]:
final_movie_rating

array([[2301.000, 3.633, 56.000, 3.183],
       [2302.000, 5.032, 55.000, 2.806],
       [2303.000, 4.170, 51.000, 3.147],
       ...,
       [2348.000, 4.336, 59.000, 3.133],
       [2349.000, 3.533, 45.000, 3.429],
       [2350.000, 3.949, 60.000, 3.242]])

In [53]:
final_movie_rating.shape

(1050, 4)

display the movies rating wise,highest to lowest

In [75]:
sorted_films= final_movie_rating[final_movie_rating[:,1].argsort()[::-1]]

In [66]:
sorted_films

array([[2690.000, 10.000, 44.000, 3.166],
       [2530.000, 9.933, 59.000, 2.770],
       [2674.000, 9.675, 55.000, 3.317],
       ...,
       [3126.000, 0.715, 52.000, 2.960],
       [2839.000, 0.096, 44.000, 3.194],
       [3089.000, 0.000, 50.000, 2.844]])

saving the sorted data in a csv file

In [67]:
np.savetxt("ranked_movie_data.csv",sorted_films,delimiter=",")

In [68]:
r=np.genfromtxt("ranked_movie_data.csv",delimiter=",")

In [69]:
r

array([[2690.000, 10.000, 44.000, 3.166],
       [2530.000, 9.933, 59.000, 2.770],
       [2674.000, 9.675, 55.000, 3.317],
       ...,
       [3126.000, 0.715, 52.000, 2.960],
       [2839.000, 0.096, 44.000, 3.194],
       [3089.000, 0.000, 50.000, 2.844]])